{"trial_id": "1", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}], "values": {"units_1": 64, "units_2": 32, "learning_rate": 0.001}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n\nDetected at node compile_loss/sparse_categorical_crossentropy/Cast defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/var/folders/8j/f0xtldm91_1c2bpdr69fxgzw0000gn/T/ipykernel_25976/4053678066.py\", line 33, in <module>\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 329, in fit\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 122, in one_step_on_iterator\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 110, in one_step_on_data\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 60, in train_step\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/trainers/trainer.py\", line 323, in compute_loss\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/trainers/compile_utils.py\", line 605, in __call__\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/trainers/compile_utils.py\", line 641, in call\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/losses/loss.py\", line 38, in __call__\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/utils/tree.py\", line 239, in map_structure\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/optree/ops.py\", line 594, in tree_map\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/losses/loss.py\", line 39, in <lambda>\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/ops/core.py\", line 495, in convert_to_tensor\n\n  File \"/Users/eugenio/Library/CloudStorage/OneDrive-Personal/UIDE/2024 Maestri\u0301a Ciencia de Datos y Ma\u0301quinas de Aprendizaje mencio\u0301n IA/Contenidos/Notebooks_DataMining/.venv/lib/python3.11/site-packages/keras/src/backend/tensorflow/core.py\", line 121, in convert_to_tensor\n\nCast string to float is not supported\n\t [[{{node compile_loss/sparse_categorical_crossentropy/Cast}}]] [Op:__inference_one_step_on_iterator_2945]\n"}